name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Déploie dès que vous poussez sur la branche 'main'
  workflow_dispatch: # Permet de lancer le déploiement manuellement depuis GitHub

# Autorise l'action à cloner le dépôt et à publier sur Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Install, build, and upload your site output
        uses: withastro/action@v3
        # L'action détecte automatiquement si vous utilisez npm, pnpm, bun ou yarn

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4